// Generated by Wrangler on Thu Aug 01 2024 21:11:43 GMT+0800 (中国标准时间)
// by running `wrangler types`

interface Env {
	NEXT_ENDPOINT: "https://mail.leafyee.xyz/api/receive";
	PEER_AUTH_KEY: "sdfuas43r34t4t4we23232243";
}
